# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_no', models.IntegerField(unique=True)),
                ('prob_title', models.CharField(max_length=255)),
                ('prob_content', models.TextField()),
                ('sol_method_name', models.CharField(max_length=255)),
                ('input_parser_type', models.IntegerField(choices=[('1', 'INTEGER'), ('2', 'FLOAT'), ('3', 'STRING')], default=1)),
                ('parse_as', models.IntegerField(choices=[('1', 'SINGLE VALUE'), ('2', 'LIST'), ('3', 'LISTS'), ('4', 'MATRIX')], default=1)),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prob_no'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='algopraxis.Problem')),
            ],
        ),
    ]
