# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='lang_mode',
            field=models.CharField(choices=[('python', 'Python3'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=20),
        ),
    ]
