# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algopraxis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='solution',
            name='lang_mode',
            field=models.CharField(choices=[('python', 'Python3'), ('java', 'Java'), ('c_cpp', 'C++')], default='python', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('user', 'problem', 'lang_mode')]),
        ),
    ]
