# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0002_auto_20170916_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang_mode', models.CharField(choices=[('python', 'Python3'), ('java', 'Java'), ('c_cpp', 'C++')], max_length=20)),
                ('main_code', models.TextField()),
                ('start_code', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codesets', to='algopraxis.Problem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='codeset',
            unique_together=set([('problem', 'lang_mode')]),
        ),
    ]
