# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0003_auto_20170612_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='ext_obj',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_parser_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='parsing_method',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution_method_name',
        ),
        migrations.AddField(
            model_name='problem',
            name='main_file_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_start_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
