# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0003_auto_20170917_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeset',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='main_file_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution_start_code',
        ),
    ]
