# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0003_problem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='content',
            new_name='code',
        ),
    ]
