# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0004_auto_20170614_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='prob_no',
        ),
    ]
