# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopraxis', '0005_auto_20170626_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='default_testcase',
            field=models.TextField(default='[2,3,4]\n6'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
